---
title: "Modeltime Algorithm Roadmap"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Modeltime Algorithm Roadmap}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = F,
  warning = F,
  echo = F
)
```

The __`modeltime` project roadmap__ ([GitHub Issue #5](https://github.com/business-science/modeltime/issues/5)) tracks the overall development of the Modeltime Ecosystem of forecasting packages.  

## Learning Modeltime

> Modeltime is a cutting-edge ecosystem for forecasting using strategies and best practices that won or placed highly in major forecasting competitions. 

We have a state-of-the-art [Time Series Forecasting Course (DS4B 203-R)](https://university.business-science.io/p/ds4b-203-r-high-performance-time-series-forecasting/) that teaches the `modeltime` ecosystem and `timetk` (Machine Learning, Deep Learning, and Feature Engineering for Time Series). Take this course to become the forecasting expert for your organization. 

## Forecast Algorithms

These algorithms are provided in the base `modeltime` package. Refer to the [API Function Reference.](https://business-science.github.io/modeltime/reference/index.html#section-algorithms)  

- [x] __ARIMA__ - See `arima_reg()`
- [x] __Exponential Smoothing (ETS)__: See `exp_smoothing()`
- [x] __STLM__ - Decomposition Models - [See `seasonal_reg()`](https://business-science.github.io/modeltime/reference/seasonal_reg.html)
- [x] __TBATS__ - [See `seasonal_reg()`](https://business-science.github.io/modeltime/reference/seasonal_reg.html)
- [x] __NNETAR__ - [See `nnetar_reg()`](https://business-science.github.io/modeltime/reference/nnetar_reg.html)
- [x] __Theta Method__ [See `exp_smoothing()`] (#93)
- [x] __CROSTON__ [See `exp_smoothing()`] (#98)

## Prophet Algorithm

These algorithms are provided in the base `modeltime` package. Refer to the [API Function Reference.](https://business-science.github.io/modeltime/reference/index.html#section-algorithms)

- [x] __Prophet__ - See `prophet_reg()`

## Boosted Algorithms

These algorithms use `xgboost` to improve performance on detecting seasonality while using the base model (e.g. prophet) for trend. These algorithms are provided in the base `modeltime` package. Refer to the [API Function Reference.](https://business-science.github.io/modeltime/reference/index.html#section-algorithms)

- [x] __Prophet Boost__ - See `prophet_boost()`
- [x] __Arima Boost__ - See `arima_boost()`

## Ensembles (Stacking, Averaging)

Please refer to `modeltime.ensemble` R package: https://business-science.github.io/modeltime.ensemble/

- [x] __Stacking__ - [See `modeltime.ensemble::ensemble_model_spec()`](https://business-science.github.io/modeltime.ensemble/reference/ensemble_model_spec.html)
- [x] __Averaging__ - [See `modeltime.ensemble::ensemble_average()`](https://business-science.github.io/modeltime.ensemble/reference/ensemble_average.html)
- [x] __Weighted Averaging__ - [See `modeltime.ensemble::ensemble_weighted()`](https://business-science.github.io/modeltime.ensemble/reference/ensemble_weighted.html)

## Autoregressive (Recursive) Forecasting 

Recursive forecasting is required when __Lags of Features < Forecast Horizon__. Please refer to the __`recursive()`__ function that allows any model to be converted into a recursive prediction model: https://business-science.github.io/modeltime/reference/recursive.html

- [x] __Recursive for Single Time Series__ - [Can be implemented using `recursive()`](https://business-science.github.io/modeltime/reference/recursive.html)
- [x] __Recursive for Panel Data (Multiple Time Series)__ - Follow #67 
- [x] __Recursive Ensembles__ - Tracked with #86. Refer to `modeltime.ensemble` for development efforts.  https://business-science.github.io/modeltime.ensemble/

## Resampling & Backtesting

- [x] Please refer to `modeltime.resample` for backtesting and resampling time series: https://business-science.github.io/modeltime.resample/index.html

## GluonTS (Deep Learning)

Please refer to `modeltime.gluonts` R package: https://github.com/business-science/modeltime.gluonts

- [x] __DeepAR__ - [See `modeltime.gluonts::deep_ar()`](https://business-science.github.io/modeltime.gluonts/reference/deep_ar.html)
- [x] __N-BEATS__ - [See `modeltime.gluonts::nbeats()`](https://business-science.github.io/modeltime.gluonts/reference/nbeats.html)

## H2O AutoML (Automatic Machine Learning)

This project is being managed via `modeltime.h2o`: https://github.com/business-science/modeltime.h2o

- [x] H2O AutoML Backend (business-science/modeltime.h2o#1)

## Baseline Models

Refer to baseline algorithms #37 

- [x] Naive & Seasonal Naive - [See `naive_reg()`](https://business-science.github.io/modeltime/reference/naive_reg.html)
- [x] Mean & Median Window Forecasts - [See `window_reg()`](https://business-science.github.io/modeltime/reference/window_reg.html)

## General Additive Models (GAMs)

We are currently working with the `parsnip` team to reach a solution. 

- [ ] GAMs (`mgcv`)


## GARCH Models

Refer to `garchmodels` ([Website](https://albertoalmuinha.github.io/garchmodels/), [GitHub](https://github.com/AlbertoAlmuinha/garchmodels)).

- [x] GARCH
- [x] RUGARCH
- [x] RMGARCH

## Bayesian Models

Refer to `bayesmodels` ([Website](https://albertoalmuinha.github.io/bayesmodels/), [GitHub](https://github.com/AlbertoAlmuinha/bayesmodels))

- [x] __Sarima__: `bayesmodels` connects to the `bayesforecast` package.
- [x] __Garch__: `bayesmodels` connects to the `bayesforecast` package.
- [x] __Random Walk (Naive)__: `bayesmodels` connects to the `bayesforecast` package.
- [x] __State Space Model__: `bayesmodels` connects to the `bayesforecast` and `bsts` packages.
- [x] __Stochastic Volatility Model__: `bayesmodels` connects to the `bayesforecast` package.
- [x] __Generalized Additive Models (GAMS)__: `bayesmodels` connects to the `brms` package.
- [x] __Adaptive Splines Surface__: `bayesmodels` connects to the `BASS` package.
- [x] __Exponential Smoothing__: `bayesmodels` connects to the `Rglt` package.

## Boosted Models: CatBoost, LightGBM

Refer to `boostime` ([GitHub](https://github.com/AlbertoAlmuinha/boostime)).

- [x] ARIMA + Catboost
- [x] ARIMA + LightGBM
- [x] Prophet + Catboost
- [x] Prophet + LightGBM

## Vector Autoregression (VAR)

Investigate whether or not tools are needed to support VAR modeling. It's unclear whether or not a separate toolset is required beyond the core system. User input required. Follow GH Issue #77.

## Spark & Dask: Scalable Compute

Investigate the possibility of adding Spark and Dask backends to improve scalability of modeltime. 

- [ ] Spark Backend #105 
- [ ] Dask Backend #106 

## LinkedIn Greykite

Investigate algorithm. Determine if backend has value. https://linkedin.github.io/greykite/docs/0.1.0/html/index.html
